# Generate example

In [4]:
import pandas as pd
import numpy as np
import os
data_path = "../Data/nyctaxi"
os.chdir(data_path)

In [18]:
ID = 0

In [19]:
N = 365
np.random.seed(ID)
ts = pd.DataFrame(
    {"date": pd.date_range(start='2021-01-01', periods=N),
     "value": np.random.randint(0, high=100,size=N)})


In [21]:
f"{ID:05d}"

'00000'

In [11]:
np.random.randint(0, high=100,size=5)

array([ 2, 29, 50, 34, 58])

In [12]:
np.random.randint(0, high=100,size=5)

array([59, 91, 64, 63,  7])

In [13]:
np.random.seed(0)
np.random.randint(0, high=100,size=5)

array([44, 47, 64, 67, 67])

In [14]:
np.random.seed(0)
np.random.randint(0, high=100,size=5)

array([44, 47, 64, 67, 67])